name: My First GitHub Action Bot

on:
  schedule:
    - cron: '*/15 * * * *'
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Download our code to the virtual computer
        uses: actions/checkout@v4

      - name: 2. Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 3. Run the python script with Secrets!
        env:
          # Pull the encrypted key securely from GitHub Secrets
          MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
        run: python ping.py
